export default [
  {
    name: 'connectionSettings',
    title: 'Connection Settings',
    settings: [
      {
        name: 'scheme',
        title: 'Connection Scheme',
        subtitle: '',
        caption: '',
        description: '',
        helptext: 'Das ist der Helptext für dieses Setting.',
        inputType: 'select',
        options: [
          { value: 'https', text: 'https:// (secure SSL connection)' },
          { value: 'http', text: 'http:// (normal unsecure connection)' },
        ],
        rules: {
          required: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'host',
        title: 'Host',
        subtitle: 'host name or IP address',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          required: true,
          host: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'port',
        title: 'Port',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          required: true,
          port: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'username',
        title: 'Username',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: false,
      },
      {
        name: 'password',
        title: 'Password',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: false,
      },
      {
        name: 'basepath',
        title: 'Reverse Proxy Path',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          relativePath: true,
        },
        isAdvancedSetting: true,
      },
    ],
    hasConnectionTest: true,
    isCategorySetting: false,
    nextButton: 'Test Connection',
  },
  {
    name: 'additionalSettings',
    title: 'Additional Settings',
    settings: [
      {
        name: 'addPaused',
        title: 'Add as paused',
        subtitle: '',
        caption: 'add NZB file in paused mode',
        description: '',
        helptext: '',
        inputType: 'switch',
        rules: {},
        isAdvancedSetting: false,
      },
    ],
    hasConnectionTest: false,
    isCategorySetting: false,
    nextButton: 'Weiter',
  },
  {
    name: 'category',
    title: 'Kategorien',
    settings: [
      {
        name: 'useCategories',
        title: 'Kategorien verwenden',
        subtitle: '',
        caption: 'Verwendung von Kategorien aktivieren',
        description: '',
        helptext: '',
        inputType: 'switch',
        rules: {},
        isAdvancedSetting: false,
      },
    ],
    hasConnectionTest: false,
    isCategorySetting: true,
    nextButton: 'Save',
  },
];
