export default [
  {
    name: 'connectionSettings',
    title: 'Connection Settings',
    settings: [
      {
        name: 'scheme',
        title: 'Connection Scheme',
        subtitle: '',
        caption: '',
        description: '',
        helptext: 'Das ist der Helptext für dieses Setting.',
        inputType: 'select',
        options: [
          { value: 'https', text: 'https:// (secure SSL connection)' },
          { value: 'http', text: 'http:// (normal unsecure connection)' },
        ],
        rules: {
          required: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'host',
        title: 'Host',
        subtitle: 'host name or IP address',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          required: true,
          host: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'port',
        title: 'Port',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          required: true,
          port: true,
        },
        isAdvancedSetting: false,
      },
      {
        name: 'username',
        title: 'Username',
        subtitle:
          'This user needs to have sufficient rights to use the DownloadStation',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: false,
      },
      {
        name: 'password',
        title: 'Password',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: false,
      },
      {
        name: 'basepath',
        title: 'Reverse Proxy Path',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {
          relativePath: true,
        },
        isAdvancedSetting: true,
      },
      {
        name: 'basicAuthUsername',
        title: 'Basic HTTP Authentication Username',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: true,
      },
      {
        name: 'basicAuthPassword',
        title: 'Basic HTTP Authentication Password',
        subtitle: '',
        caption: '',
        description: '',
        helptext: '',
        inputType: 'text',
        rules: {},
        isAdvancedSetting: true,
      },
    ],
    hasConnectionTest: true,
    isCategorySetting: false,
    nextButton: 'Test Connection',
  },
];
